### ISSUE TITLE
Main TGstation "MUST PORT" list

### ISSUE THREAD

**Issue by DoctoreMad** [RoleplayRascal/-8ch-station#90]
I feel like they've coded a lot of bugfixes we didn't merge yet. Would it be simpler to merge form them and then rollback or is this faster?
Either way, post anything applicable.

On my list I've got...
(Bugfix) https://github.com/tgstation/tgstation/pull/29283
(Bugfix) https://github.com/tgstation/tgstation/pull/29495
Possibly others, but I can't be assed to find them right now.

**Comment by chaosyourgod** [comment]
>put in fixes for bugs which aren't on our codebase that we know of yet
what could possibly go wrong?

**Comment by DoctoreMad** [comment]
Oh come on, cyborgs have no way to handle oxygen/toxin damage since their implementation on both TGstation and /vg/station. If somehow a cyborg taking oxygen/toxin damage DOESN'T bug I'll be legitimately surprised.

**Comment by DoctoreMad** [comment]
To add on that list, that circle code for ghosts makes you follow players 99% smoother than "teleport to player location every 0.1 seconds" code we currently have.

**Comment by KyleBaran** [comment]
Please be aware that I am doing a PR for a large refactor to health status effect, such as deafness or blindness. This is a large commit across [b]71 files[/b], so you might need to do a little bit more than a direct copypaste into the code, now.

Specifically, mobs now have a mob/health_status/ object which tracks these. For most code, you'll want to put it into the [variable name], rather than [variable name_intensity].

**Comment by chaosyourgod** [comment]
considering cyborgs do not take oxy or toxin damage in our code base as far as I know we don't need it and "portals" on the shuttle means what?

**Comment by DoctoreMad** [comment]
>cyborgs do not take oxy or toxin damage in our code

Weapons can directly deal oxygen/toxin damage. For example, try using the RIPLEY clamp on a Borg and see that he's **INCAPACITATED FOREVER**.

**Comment by DoctoreMad** [comment]
inb4 edge case

**Comment by chaosyourgod** [comment]
whelp 
![ss 2017-08-20 at 12 56 04](https://user-images.githubusercontent.com/7388412/29490880-6dcdbc52-8542-11e7-8c0e-be93ff47af84.png)
you're correct

**Comment by DoctoreMad** [comment]
Wait I should just open a individual list for all those issues
