### ISSUE TITLE
'joy' recipe doesn't work

### ISSUE THREAD

**Issue by GeneralGoose** [RoleplayRascal/-8ch-station#91]
https://github.com/chaosyourgod/-8ch-station/blob/master/code/modules/reagents/recipes/recipe_drug.dm#L50

does nothing

I couldn't find '2happy' in reagents/reagent_drug or anything that can resemble it 
I guess the 'result' just doesn't exist in the code or is written incorrectly

**Comment by chaosyourgod** [comment]
it was removed on early servers because it was a shitty meme thing which did fucking nothing, we're wanting to add it back in but only if we can give it what its intention function was

**Comment by KyleBaran** [comment]
I'll close this for now, but I'll put a note in the feature request stuff
