### ISSUE TITLE
slimes befriending monkeys?

### ISSUE THREAD

**Issue by GeneralGoose** [RoleplayRascal/-8ch-station#96]
Im not sure if this behaviour is intended
gold adult slime (797) telepathically chirps, "The monkey (706)... friend..."
It refused to eat the monkey, but ate a different one
I ended up giving the monkey to a different slime

**Comment by DoctoreMad** [comment]
Its not intended on main TGstation code but also why would you follow TGstation code?
Stop lazy feeding your slimes, xenobiology is a actual job.

**Comment by RoleplayRascal** [comment]
Generally slimes befriend any mob that has been around it for a given amount of time. This also included monkeys. This doesn't need to be fixed.
